import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "../styles/globals.css";


const lato = Lato({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Next.js Mongo Template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={lato.className}
      >
        {children}
      </body>
    </html>
  );
}
